services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString

databases:
  - name: symfony-db
    plan: free
    postgresMajorVersion: 16
